#include "HTMLWriter.h"
#include <fstream>
using namespace std;

HTMLWriter::HTMLWriter() {
	_filename = " NoName.html";

	_fontname = "±¼¸²";
	_fontsize = 3;
	_fontcolor = "black";
}
HTMLWriter::~HTMLWriter() {

}
void HTMLWriter::SetFont(const string& fontname, int fontsize, const string& fontcolor) {
	_fontname = fontname;
	_fontsize = fontsize;
	_fontcolor = fontcolor;
}
void HTMLWriter::Write()
{
	ofstream of(_filename.c_str());

	of << "<html><head><title>This document was generated by HTMLWriter</title></head></html>";
	of << "<h1>Content</h1>";
	of << "<font name = " << _fontname << "'size='" << _fontsize << "'color='" << _fontcolor << "'>";
	of << _content;
	of << "</font>";
	of << "</body></html>";

}
HTMLWriter::HTMLWriter(const string& filename, const string& content) : DocWriter(filename, content) {
	_fontname = "±¼¸²";
	_fontsize = 3;
	_fontcolor = "black";
}